### ISSUE TITLE
Missing manifest for out-of-the-box call of ./bild.py install

### ISSUE THREAD

**Issue by g2graman** [antlr/symtab#1]
Similar to [this bug](https://github.com/antlr/antlr4/issues/864), after cloning the repository and invoking

```
./bild.py -debug install
```

I get

```
...
build _mkjar
[04/28/15 05:00:50 require ./bild.py:70 bilder.py:430] build _mkjar
Traceback (most recent call last):
  File "/home/g2graman/Desktop/translateJS/tmp/symtab/bilder.py", line 857, in processargs
    target()
  File "./bild.py", line 105, in install
    require(mkjar)
  File "/home/g2graman/Desktop/translateJS/tmp/symtab/bilder.py", line 426, in require
    target()
  File "./bild.py", line 101, in mkjar
    _mkjar()
  File "./bild.py", line 89, in _mkjar
    manifest = manifest % (VERSION, os.getlogin(), get_java_version(), VERSION)
OSError: [Errno 2] No such file or directory
[04/28/15 05:00:50 processargs ./bild.py:171 bilder.py:860] [Errno 2] No such file or directory
bild succeeded
```

Was there a missing step to generate the according manifest file for `_mkjar`?

**Comment by parrt** [comment]
check the log. missing java version or something?

**Comment by g2graman** [comment]
Here is my `bild.log`:

```
[04/28/15 22:26:52 <module> ./bild.py:54 bilder.py:124] platform=linux2
[04/28/15 22:26:52 <module> ./bild.py:54 bilder.py:125] jdk={'1.6': '/usr/lib/jvm/java-1.6.0-openjdk-amd64', '1.7': '/usr/lib/jvm/java-1.7.0-openjdk-amd64'}
[04/28/15 22:26:52] require mkjar
[04/28/15 22:26:52 require ./bild.py:105 bilder.py:422] require mkjar
[04/28/15 22:26:52] require compile
[04/28/15 22:26:52 require ./bild.py:70 bilder.py:422] require compile
[04/28/15 22:26:52 javac ./bild.py:66 bilder.py:503] 1.8.0_45
[04/28/15 22:26:52 javac ./bild.py:66 bilder.py:511] javac -d /home/g2graman/Desktop/translateJS/tmp/symtab/out -cp /home/g2graman/Desktop/translateJS/tmp/symtab/out:/home/g2graman/.bild/jars/antlr-4.5-complete.jar: -source 1.8 -target 1.8 -Xlint -Xlint:-serial -g -sourcepath src /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/PredefinedScope.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/InvalidType.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/GlobalScope.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/FunctionType.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/DataAggregateSymbol.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/PointerType.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/TypedSymbol.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/BaseScope.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/Utils.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/BaseSymbol.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/PrimitiveType.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/LocalScope.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/SymbolWithScope.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/VariableSymbol.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/FieldSymbol.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/Type.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/FunctionSymbol.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/Scope.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/MemberSymbol.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/ArrayType.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/ParameterSymbol.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/ClassSymbol.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/Symbol.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/StringTable.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/TypeAlias.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/SymbolTable.java /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/MethodSymbol.java
[04/28/15 22:26:54 javac ./bild.py:66 bilder.py:511] /home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/BaseScope.java:37: warning: [unchecked] unchecked conversion
        return (List)scopes; // force it to cast
               ^
  required: List<Scope>
  found:    List
/home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/DataAggregateSymbol.java:43: warning: [unchecked] unchecked cast
        return (List<MemberSymbol>)super.getSymbols();
                                                   ^
  required: List<MemberSymbol>
  found:    List<CAP#1>
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Symbol from capture of ? extends Symbol
/home/g2graman/Desktop/translateJS/tmp/symtab/src/org/antlr/symtab/DataAggregateSymbol.java:48: warning: [unchecked] unchecked cast
        return (Map<String, ? extends MemberSymbol>)super.getMembers();
                                                                    ^
  required: Map<String,? extends MemberSymbol>
  found:    Map<String,CAP#1>
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Symbol from capture of ? extends Symbol
3 warnings
[04/28/15 22:26:54] build _mkjar
[04/28/15 22:26:54 require ./bild.py:70 bilder.py:430] build _mkjar
[04/28/15 22:26:54 processargs ./bild.py:171 bilder.py:860] [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/g2graman/Desktop/translateJS/tmp/symtab/bilder.py", line 857, in processargs
    target()
  File "./bild.py", line 105, in install
    require(mkjar)
  File "/home/g2graman/Desktop/translateJS/tmp/symtab/bilder.py", line 426, in require
    target()
  File "./bild.py", line 101, in mkjar
    _mkjar()
  File "./bild.py", line 89, in _mkjar
    manifest = manifest % (VERSION, os.getlogin(), get_java_version(), VERSION)
OSError: [Errno 2] No such file or directory
```

@parrt, any idea how to fix this?
